# Generated by Django 4.2 on 2023-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_name_ar_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
